---
- hosts: localhost
  connection: local
  become: true
  roles:
    - role: "geerlingguy.pip"
    - role: "geerlingguy.docker"
  vars:
    pip_package: python3-pip
    pip_install_packages:
    - name: docker

    # Override until Docker officially supports 20.04 "focal"
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} bionic {{ docker_apt_release_channel }}"

    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted

    docker_install_compose: false
  tasks:
    - name: Ensure data directory exists
      file:
        path: /data
        mode: u+rw,g+rw,o-rw
        state: directory
    - name: Ensure Minecraft docker container is running
      docker_container:
        detach: true
        env:
          CONSOLE: "false" # TODO is this needed for paperMC?
          GUI: "false"
          EULA: "true"
          TYPE: "PAPER"
        image: "itzg/minecraft-server:adopt13"
        mounts:
          - consistency: consistent
            read_only: false
            target: /data
            source: /data
            type: bind # maybe this should be 'volume', but the cloud should abstract that from us
        name: mc-server
        published_ports:
          - "25565:25565" # main server port
          - "25575:25575" # rcon port
        pull: true
        restart_policy: 'unless-stopped'
        state: started
